### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by vutuan9182** [nerdgeneration/www.sh#1]
This is interesting. I don't use bash in web services anymore berfore.

Could you provide the Dockerfile to help people have a quick your work.

**Comment by nerdgeneration** [comment]
I didn't expect anyone to actually *run* this, but sure. I've made a Dockerfile but am having some errors. I'll fix those before I push.

**Comment by nerdgeneration** [comment]
I'd say a year is a good response time?

It now runs in Docker with Apache.
