### ISSUE TITLE
fix `declare` statement at end for Mac

### ISSUE THREAD

**Issue by svaniksharma** [nerdgeneration/www.sh#2]
I ran `bash www.sh` and it returned:
```
www.sh: line 111: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

For context, I'm running a macOS Mojave.

**Comment by svaniksharma** [comment]
Turns out the issue has to do with the fact that Apple provides bash version ~ 3.0 by default, so you have to update with Homebrew in order for it to read the `declare` command.

**Comment by nerdgeneration** [comment]
Yup. Thanks for the readme commit :)
